# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ursafespace

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js application
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          OWNER_EMAIL: ${{ secrets.OWNER_EMAIL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        run: npm run build

      - name: Run tests
        run: npm run test --if-present

      - name: Create deployment package
        run: |
          mkdir deployment-package
          cp -r .next deployment-package/
          cp -r src deployment-package/
          cp -r public deployment-package/
          cp package*.json deployment-package/
          cp -r node_modules deployment-package/
          cp web.config deployment-package/
          cp server.js deployment-package/
          cp run.js deployment-package/
          cp startup.sh deployment-package/
          cp .deployment deployment-package/
          cp next.config.js deployment-package/
          chmod +x deployment-package/startup.sh

          # Verify deployment package
          echo "=== Deployment Package Contents ==="
          ls -la deployment-package/
          echo "=== Package.json check ==="
          cat deployment-package/package.json | grep -A 5 -B 5 "scripts"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment-package/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_87FEFBE2234841E0B2D30248C5EAD5F1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B9C75E24027E40CBAD4B41312C0B8B87 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_20553EF97A1040CD9F6F655DD94AE874 }}

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "ursafespace"
          slot-name: "Production"
          package: .
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          OWNER_EMAIL: ${{ secrets.OWNER_EMAIL }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
